//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terlik_yeni.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terlik_yeni.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEDEN PELUCHE.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Alanı.
        /// </summary>
        public static string AboutHizmet {
            get {
                return ResourceManager.GetString("AboutHizmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 yılı aşkın tecrübemiz ile Türkiye ve Dünya genelinde önde gelen markalara trend ev terlikleri üretiyoruz..
        /// </summary>
        public static string AboutHizmetAç {
            get {
                return ResourceManager.GetString("AboutHizmetAç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın İstihdamı.
        /// </summary>
        public static string AboutKadın {
            get {
                return ResourceManager.GetString("AboutKadın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %90&apos;ını kadın çalışanların oluşturduğu ekibimiz kadın istihdamının her zaman arkasındadır..
        /// </summary>
        public static string AboutKadınAç {
            get {
                return ResourceManager.GetString("AboutKadınAç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Memnuniyeti.
        /// </summary>
        public static string AboutMüşeteri {
            get {
                return ResourceManager.GetString("AboutMüşeteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef kitlelerimizin taleplerine hızlı ve akılcı çözümler sunarak müşteri memnuniyetini en üst düzeyde tutmayı hedefliyoruz..
        /// </summary>
        public static string AboutMüşetrtiAç {
            get {
                return ResourceManager.GetString("AboutMüşetrtiAç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 saat hizmet.
        /// </summary>
        public static string AboutSaat {
            get {
                return ResourceManager.GetString("AboutSaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 saat hizmetinizdeyiz; sorularınızı yanıtlamak, ihtiyaçlarınıza çözüm bulmak ve sizin için her an yanınızda olmak bizim için bir ayrıcalıktır..
        /// </summary>
        public static string AboutSaatAç {
            get {
                return ResourceManager.GetString("AboutSaatAç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasarım Trendleri.
        /// </summary>
        public static string AboutTasarım {
            get {
                return ResourceManager.GetString("AboutTasarım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern, dinamik ve eğlenceli tasarımlarımız ile trendleri yakından takip ediyoruz..
        /// </summary>
        public static string AboutTasarımAç {
            get {
                return ResourceManager.GetString("AboutTasarımAç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Nesil Teknoloji.
        /// </summary>
        public static string AboutTech {
            get {
                return ResourceManager.GetString("AboutTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünlerimizin kalite ve konforunu yeni nesil üretim teknolojileri ile artırarak geliştirmeye her geçen gün devam ediyoruz..
        /// </summary>
        public static string AboutTechAç {
            get {
                return ResourceManager.GetString("AboutTechAç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gondol.
        /// </summary>
        public static string Gondol {
            get {
                return ResourceManager.GetString("Gondol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Botu.
        /// </summary>
        public static string HomeBoots {
            get {
                return ResourceManager.GetString("HomeBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Ayakkabıları.
        /// </summary>
        public static string HomeShoes {
            get {
                return ResourceManager.GetString("HomeShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüksek yoğunluklu hafızalı köpük teknolojisi ile her adımda yastıklama hissi..
        /// </summary>
        public static string IndexSlider1 {
            get {
                return ResourceManager.GetString("IndexSlider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hafif ve yumuşak tabanı sayesinde adımlara uyum sağlar..
        /// </summary>
        public static string IndexSlider2 {
            get {
                return ResourceManager.GetString("IndexSlider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renkli ve eğlenceli çocuk desenleri ile severek kullanılan Peluche ev terlikleri rahat hareket etmelerini sağlar..
        /// </summary>
        public static string IndexSlider3 {
            get {
                return ResourceManager.GetString("IndexSlider3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panduf.
        /// </summary>
        public static string Panduf {
            get {
                return ResourceManager.GetString("Panduf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çocuk.
        /// </summary>
        public static string ProductChild {
            get {
                return ResourceManager.GetString("ProductChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        public static string ProductMen {
            get {
                return ResourceManager.GetString("ProductMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünlerimiz.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        public static string ProductWomen {
            get {
                return ResourceManager.GetString("ProductWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deniz Ayakkabısı.
        /// </summary>
        public static string Sea {
            get {
                return ResourceManager.GetString("Sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terlik.
        /// </summary>
        public static string Slipper {
            get {
                return ResourceManager.GetString("Slipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terlikleri.
        /// </summary>
        public static string SlipperHeader {
            get {
                return ResourceManager.GetString("SlipperHeader", resourceCulture);
            }
        }
    }
}
